# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba4df4d5022a138f8a088c34881cae8d9fab6d652b1c19dd7140d819208dc1516cc0ea6c9e2a3b6741e1073bab20d2f4e8960bc5a53146bf5643429fb7a92668

test:
  secret_key_base: dce8a38428c02b8e90abd9fe8644bb3ca48e3b6b83dc8805d82adb73e824f6dcb52176d26a829a874c5076776bd11e4c1ef6c88d95bef72f7f5e29e5229cfe11

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
